### ISSUE TITLE
Input image should be opaque

### ISSUE THREAD

**Issue by zuffik** [aeirola/react-native-svg-app-icon#30]
why?

**Comment by aeirola** [comment]
The restriction is due to the fact that many of the generated icon formats, such as iOS icons and android adaptive icons, do not support transparency. If all the supported icon formats would allow transparency, this restriction would not be needed 

It would of course be possible for the tool to fill in the transparent parts with some arbitrary colour, but that would mean that the icons might look different on different devices. Unfortunately, that would kind of defeat the purpose of the tool which aims to generate the same icon for all platforms. If you are looking for platform-specific icons, then this tool isn't the right one for that task.

What would you have hoped to have happened when passing a transparent icon to the tool?

**Comment by zuffik** [comment]
Thanks for quick response. I was hoping that some color (white, or alternatively passed via CLI option) will be added to output image.

**Comment by aeirola** [comment]
Okay, fair enough. Do you have a specific use case where the background colour couldn't just achieved by adding an opaque square in the source SVG file? 

I'm hoping on keeping the tool as simple as possible, having only one clear way of doing specific things (such as adding background colours).

**Comment by zuffik** [comment]
For example in my case I am generating 2 sets of icons from single svg file: favicon for web and native app icon. The svg is not the final icon and will be definitely changed in the future. Favicons are allowed to contain transparent parts in image so I need to create extra image just for this generator where the background is white. 

PS: the svg image has to have exact dimensions  (108x108px) but this could be also achieved in the generator itself. Size of image is not the problem for favicon so I just resized it but I'd like to avoid copying the file just for adding a background.

**Comment by aeirola** [comment]
Ah, yeah. That makes sense. Didn't consider the case where the same file would be used elsewhere as well.

Hmm, maybe I could incorporate this with support for proper adaptive icon backgrounds. So instead of specifying a solid color, there would be a separate icon-background.svg which would be used for the background in case the (foreground) icon contains transparency.

How does this sound?

**Comment by zuffik** [comment]
Sounds great. If someone wants to use for example a gradient as background this would be perfect. But in simple case also the cli option would be appreciated. Anyway thanks and I will be waiting for update.

**Comment by aeirola** [comment]
Ok, good. Created a separate issue #31 for the new feature. Hoping to be able to work on that next weekend. Closing this issue as the question seems to be answered.
